image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -e .[dev]

stages:
  # - test_classification
  - test_regression

# test-classification:
#   stage: test_classification
#   script:
#     - pytest tests/test_classification_seed.py

test-regression:
  stage: test_regression
  script:
    - pytest tests/test_regression_seed.py
